export const UniversityData: string[] = [
  'Abdullah Gül Üniversitesi',
  'Acıbadem Üniversitesi',
  'Ada Kent Üniversitesi',
  'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
  'Adıyaman Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Akdeniz Karpaz Üniversitesi',
  'Akdeniz Üniversitesi',
  'Aksaray Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Alanya Üniversitesi',
  'Altınbaş Üniversitesi',
  'Amasya Üniversitesi',
  'Anadolu Üniversitesi',
  'Ankara Bilim Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Medipol Üniversitesi',
  'Ankara Müzik ve Güzel Sanatlar Üniversitesi',
  'Ankara Sosyal Bilimler Üniversitesi',
  'Ankara Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Antalya Belek Üniversitesi',
  'Antalya Bilim Üniversitesi',
  'Ardahan Üniversitesi',
  'Arkın Yaratıcı Sanatlar Ve Tasarım Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Ataşehir Adıgüzel Meslek Yüksekokulu',
  'Atatürk Üniversitesi',
  'Atılım Üniversitesi',
  'Avrasya Üniversitesi',
  'Aydın Adnan Menderes Üniversitesi',
  'Bahçeşehir Kıbrıs Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Bartın Üniversitesi',
  'Başkent Üniversitesi',
  'Batman Üniversitesi',
  'Bayburt Üniversitesi',
  'Beykoz Üniversitesi',
  'Bezmialem Vakıf Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Bilkent Üniversitesi',
  'Bingöl Üniversitesi',
  'Biruni Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Boğaziçi Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Burdur Mehmet Akif Ersoy Üniversitesi',
  'Bursa Teknik Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Çağ Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Çankaya Üniversitesi',
  'Çankırı Karatekin Üniversitesi',
  'Çukurova Üniversitesi',
  'Demiroğlu Bilim Üniversitesi',
  'Dicle Üniversitesi',
  'Doğu Akdeniz Üniversitesi',
  'Doğuş Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Düzce Üniversitesi',
  'Ege Üniversitesi',
  'Erciyes Üniversitesi',
  'Erzincan Binali Yıldırım Üniversitesi',
  'Erzurum Teknik Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  'Fatih Sultan Mehmet Vakıf Üniversitesi',
  'Fenerbahçe Üniversitesi',
  'Fırat Üniversitesi',
  'Galatasaray Üniversitesi',
  'Gazi Üniversitesi',
  'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
  'Gaziantep Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'Giresun Üniversitesi',
  'Girne Amerikan Üniversitesi',
  'Girne Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Hacettepe Üniversitesi',
  'Hakkari Üniversitesi',
  'Haliç Üniversitesi',
  'Harran Üniversitesi',
  'Hasan Kalyoncu Üniversitesi',
  'Hatay Mustafa Kemal Üniversitesi',
  'Hitit Üniversitesi',
  'Iğdır Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'Işık Üniversitesi',
  'İbn Haldun Üniversitesi',
  'İnönü Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'İstanbul 29 Mayıs Üniversitesi',
  'İstanbul Arel Üniversitesi',
  'İstanbul Atlas Üniversitesi',
  'İstanbul Aydın Üniversitesi',
  'İstanbul Beykent Üniversitesi',
  'İstanbul Bilgi Üniversitesi',
  'İstanbul Esenyurt Üniversitesi',
  'İstanbul Galata Üniversitesi',
  'İstanbul Gedik Üniversitesi',
  'İstanbul Gelişim Üniversitesi',
  'İstanbul Kent Üniversitesi',
  'İstanbul Kültür Üniversitesi',
  'İstanbul Medeniyet Üniversitesi',
  'İstanbul Medipol Üniversitesi',
  'İstanbul Okan Üniversitesi',
  'İstanbul Rumeli Üniversitesi',
  'İstanbul Sabahattin Zaim Üniversitesi',
  'İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu',
  'İstanbul Sağlık ve Teknoloji Üniversitesi',
  'İstanbul Şişli Meslek Yüksekokulu',
  'İstanbul Teknik Üniversitesi',
  'İstanbul Ticaret Üniversitesi',
  'İstanbul Topkapı Üniversitesi',
  'İstanbul Üniversitesi',
  'İstanbul Üniversitesi - Cerrahpaşa',
  'İstanbul Yeni Yüzyıl Üniversitesi',
  'İstinye Üniversitesi',
  'İzmir Bakırçay Üniversitesi',
  'İzmir Demokrasi Üniversitesi',
  'İzmir Ekonomi Üniversitesi',
  'İzmir Katip Çelebi Üniversitesi',
  'İzmir Kavram Meslek Yüksekokulu',
  'İzmir Tınaztepe Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'Kadir Has Üniversitesi',
  'Kafkas Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Kapadokya Üniversitesi',
  'Karabük Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Kastamonu Üniversitesi',
  'Kayseri Üniversitesi',
  'Kıbrıs Amerikan Üniversitesi',
  'Kıbrıs Batı Üniversitesi',
  'Kıbrıs İlim Üniversitesi',
  'Kıbrıs Sosyal Bilimler Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırklareli Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Kocaeli Sağlık ve Teknoloji Üniversitesi',
  'Kocaeli Üniversitesi',
  'Koç Üniversitesi',
  'Konya Gıda ve Tarım Üniversitesi',
  'Konya Teknik Üniversitesi',
  'KTO Karatay Üniversitesi',
  'Kütahya Dumlupınar Üniversitesi',
  'Kütahya Sağlık Bilimleri Üniversitesi',
  'Lefke Avrupa Üniversitesi',
  'Lokman Hekim Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Maltepe Üniversitesi',
  'Manisa Celal Bayar Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Marmara Üniversitesi',
  'MEF Üniversitesi',
  'Mersin Üniversitesi',
  'Milli Savunma Üniversitesi',
  'Mimar Sinan Güzel Sanatlar Üniversitesi',
  'Mudanya Üniversitesi',
  'Muğla Sıtkı Koçman Üniversitesi',
  'Munzur Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Necmettin Erbakan Üniversitesi',
  'Netkent Akdeniz Araştırma ve Bilim Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Nişantaşı Üniversitesi',
  'Nuh Naci Yazgan Üniversitesi',
  'Onbeş Kasım Kıbrıs Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'Ordu Üniversitesi',
  'Orta Doğu Teknik Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Ostim Teknik Üniversitesi',
  'Özyeğin Üniversitesi',
  'Pamukkale Üniversitesi',
  'Piri Reis Üniversitesi',
  'Polis Akademisi',
  'Rauf Denktaş Üniversitesi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Sabancı Üniversitesi',
  'Sağlık Bilimleri Üniversitesi',
  'Sakarya Uygulamalı Bilimler Üniversitesi',
  'Sakarya Üniversitesi',
  'Samsun Üniversitesi',
  'Sanko Üniversitesi',
  'Selçuk Üniversitesi',
  'Siirt Üniversitesi',
  'Sinop Üniversitesi',
  'Sivas Bilim ve Teknoloji Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Süleyman Demirel Üniversitesi',
  'Şırnak Üniversitesi',
  'Tarsus Üniversitesi',
  'TED Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'TOBB Ekonomi ve Teknoloji Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Toros Üniversitesi',
  'Trabzon Üniversitesi',
  'Trakya Üniversitesi',
  'Türk Alman Üniversitesi',
  'Türk Hava Kurumu Üniversitesi',
  'Ufuk Üniversitesi',
  'Uluslararası Final Üniversitesi',
  'Uluslararası Kıbrıs Üniversitesi',
  'Uşak Üniversitesi',
  'Üsküdar Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Yakın Doğu Üniversitesi',
  'Yalova Üniversitesi',
  'Yaşar Üniversitesi',
  'Yeditepe Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Yozgat Bozok Üniversitesi',
  'Yüksek İhtisas Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',
];
